### ISSUE TITLE
[Bug]: JSONDecodeError when using -S and --compliance flags

### ISSUE THREAD

**Issue by artfulbodger** [toniblyx/prowler#1663]
**What happened?**
When running an assessment with the --compliance flag, I get a JSONDecodeError when resolving previous security hub findings.

**How to reproduce it**
Steps to reproduce the behaviour:
1. Using command `prowler aws -R <role arn> --compliance cis_1.5_aws -S -M json-asff -f eu-west-1`
2. I've only tested against the same account where the EC2 instance is running.
```
Traceback (most recent call last):
        File "/usr/local/bin/prowler", line 8, in <module> sys.exit(prowler())
        File "/usr/local/lib/python3.9/dist-packages/prowler/__main__.py", line 203, in prowler resolve_security_hub_previous_findings(args.output_directory, audit_info)
        File "/usr/local/lib/python3.9/dist-packages/prowler/providers/aws/lib/security_hub/security_hub.py", line 73, in resolve_security_hub_previous_findings json_asff_file = json.load(f)
        File "/usr/lib/python3.9/json/__init__.py", line 293, in load return loads(fp.read(),
        File "/usr/lib/python3.9/json/__init__.py", line 346, in loads return _default_decoder.decode(s)
        File "/usr/lib/python3.9/json/decoder.py", line 337, in decode obj, end = self.raw_decode(s, idx=_w(s, 0).end())
        File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode raise JSONDecodeError("Expecting value", s, err.value) from None
```

**Expected behaviour**
Previous security hub findings should be resolved.

**Screenshots or Logs**
Also, you can add logs (anonymize them first!). Here a command that may help to share a log
`prowler <your arguments> --log-level DEBUG --log-file $(date +%F)_debug.log` then attach here the log file.

[2023-01-05_debug.log](https://github.com/prowler-cloud/prowler/files/10354476/2023-01-05_debug.log)

**From where are you running Prowler?**
Please, complete the following information:
 - Resource: EC2 instance
 - OS: Debian 11 AMI
 - Prowler Version 3.0.2
 - Python version [`python --version`]: 3.9.2
 - Pip version [`pip --version`]: 20.3.4
 - Installation method (Are you running it from pip package or cloning the github repo?): pip package
 - Others:

**Additional context**

**Comment by n4ch04** [comment]
Hi @artfulbodger we are going to check it and let you know once we have an answer
