### ISSUE TITLE
[Bug]: PROWLER_REPORT_LIB_PATH error with version 3.3.0

### ISSUE THREAD

**Issue by mattrawles** [toniblyx/prowler#2131]
### Steps to Reproduce

Hi,

Version 3.3.0 seems to throw an exception (it doesnt start correctly).

Version 3.2.4 on same system works fine, this is new in 3.3.0. 

Traceback (most recent call last):
  File "/mnt/c/dev/public/prowler/prowler/lib/check/check.py", line 19, in <module>
    lib = os.environ["PROWLER_REPORT_LIB_PATH"]
  File "/usr/lib/python3.9/os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'PROWLER_REPORT_LIB_PATH'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/c/dev/public/prowler/prowler.py", line 5, in <module>
    from prowler.__main__ import prowler
  File "/mnt/c/dev/public/prowler/prowler/__main__.py", line 7, in <module>
    from prowler.lib.check.check import (
  File "/mnt/c/dev/public/prowler/prowler/lib/check/check.py", line 23, in <module>
    from prowler.lib.outputs.outputs import report
  File "/mnt/c/dev/public/prowler/prowler/lib/outputs/outputs.py", line 16, in <module>
    from prowler.lib.outputs.file_descriptors import fill_file_descriptors
  File "/mnt/c/dev/public/prowler/prowler/lib/outputs/file_descriptors.py", line 12, in <module>
    from prowler.lib.outputs.html import add_html_header
  File "/mnt/c/dev/public/prowler/prowler/lib/outputs/html.py", line 18, in <module>
    from prowler.lib.utils.utils import open_file
  File "/mnt/c/dev/public/prowler/prowler/lib/utils/utils.py", line 10, in <module>
    from detect_secrets import SecretsCollection
ImportError: cannot import name 'SecretsCollection' from 'detect_secrets' (/mnt/c/dev/public/prowler/.venv-prowler/lib/python3.9/site-packages/detect_secrets/__init__.py)

### Expected behavior

Release 3.2.4 prowler starts and displays logo then starts assessment.
Clone latest version and prowler will not start.

### Actual Result with Screenshots or Logs

Traceback (most recent call last):
  File "/mnt/c/dev/public/prowler/prowler/lib/check/check.py", line 19, in <module>
    lib = os.environ["PROWLER_REPORT_LIB_PATH"]
  File "/usr/lib/python3.9/os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'PROWLER_REPORT_LIB_PATH'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/c/dev/public/prowler/prowler.py", line 5, in <module>
    from prowler.__main__ import prowler
  File "/mnt/c/dev/public/prowler/prowler/__main__.py", line 7, in <module>
    from prowler.lib.check.check import (
  File "/mnt/c/dev/public/prowler/prowler/lib/check/check.py", line 23, in <module>
    from prowler.lib.outputs.outputs import report
  File "/mnt/c/dev/public/prowler/prowler/lib/outputs/outputs.py", line 16, in <module>
    from prowler.lib.outputs.file_descriptors import fill_file_descriptors
  File "/mnt/c/dev/public/prowler/prowler/lib/outputs/file_descriptors.py", line 12, in <module>
    from prowler.lib.outputs.html import add_html_header
  File "/mnt/c/dev/public/prowler/prowler/lib/outputs/html.py", line 18, in <module>
    from prowler.lib.utils.utils import open_file
  File "/mnt/c/dev/public/prowler/prowler/lib/utils/utils.py", line 10, in <module>
    from detect_secrets import SecretsCollection
ImportError: cannot import name 'SecretsCollection' from 'detect_secrets' (/mnt/c/dev/public/prowler/.venv-prowler/lib/python3.9/site-packages/detect_secrets/__init__.py)

### How did you install Prowler?

Cloning the repository from github.com (git clone)

### Environment Resource

Tested on 

Docker container  based on python:3.9 and VM running Debian GNU/Linux 11 (bullseye)

### OS used

Docker container  based on python:3.9 and VM running Debian GNU/Linux 11 (bullseye)

### Prowler version

3.3.0

### Pip version

pip 23.0.1 from /usr/local/lib/python3.9/dist-packages/pip (python 3.9)

### Context

Started when my test container was re-built to include updated version 3.3.0.

**Comment by jfagoagas** [comment]
Hi @mattrawles, that error is due to the absence of some of the Prowler dependencies but the traceback starts when Prowler tries to import the reporting library. Could you please run `poetry shell && poetry install` to get the latest dependencies? Then, everything should run without problem.

Refer to the documentation if you need guidance during the installation https://docs.prowler.cloud/en/latest/#installation

Thanks for using Prowler!

**Comment by n4ch04** [comment]
Hi @mattrawles, did the above workaround solve your issue ?

**Comment by mattrawles** [comment]
> Hi @mattrawles, did the above workaround solve your issue ?

Hi, yes, re-installing prowler properly (as opposed to doing the dependencies manually and then just checking the repo out which is how I had been running it!). Just did pip install prowler and back to working version 3.3.0. Case of RTFM. Thanks for the pointer!

**Comment by jfagoagas** [comment]
> > Hi @mattrawles, did the above workaround solve your issue ?
> 
> Hi, yes, re-installing prowler properly (as opposed to doing the dependencies manually and then just checking the repo out which is how I had been running it!). Just did pip install prowler and back to working version 3.3.0. Case of RTFM. Thanks for the pointer!

Awesome, closing this then. We're always here to help.

Thanks for using Prowler!
