### ISSUE TITLE
[Bug]:  Run prowler with errors

### ISSUE THREAD

**Issue by ripperi8u** [toniblyx/prowler#3015]
### Steps to Reproduce

run command "prowler -v"

### Expected behavior

run prowler command normally

### Actual Result with Screenshots or Logs
```
/opt/homebrew/Cellar/prowler/3.11.0/libexec/lib/python3.12/site-packages/prowler/lib/banner.py:15: SyntaxWarning: invalid escape sequence '\|'
  """
ModuleNotFoundError: No module named '_cffi_backend'
thread '<unnamed>' panicked at 'Python API call failed', /Users/brew/Library/Caches/Homebrew/cargo_cache/registry/src/index.crates.io-6f17d22bba15001f/pyo3-0.18.3/src/err/mod.rs:790:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "/opt/homebrew/bin/prowler", line 5, in <module>
    from prowler.__main__ import prowler
  File "/opt/homebrew/Cellar/prowler/3.11.0/libexec/lib/python3.12/site-packages/prowler/__main__.py", line 10, in <module>
    from prowler.lib.check.check import (
  File "/opt/homebrew/Cellar/prowler/3.11.0/libexec/lib/python3.12/site-packages/prowler/lib/check/check.py", line 21, in <module>
    from prowler.lib.outputs.outputs import report
  File "/opt/homebrew/Cellar/prowler/3.11.0/libexec/lib/python3.12/site-packages/prowler/lib/outputs/outputs.py", line 8, in <module>
    from prowler.lib.outputs.file_descriptors import fill_file_descriptors
  File "/opt/homebrew/Cellar/prowler/3.11.0/libexec/lib/python3.12/site-packages/prowler/lib/outputs/file_descriptors.py", line 13, in <module>
    from prowler.lib.outputs.html import add_html_header
  File "/opt/homebrew/Cellar/prowler/3.11.0/libexec/lib/python3.12/site-packages/prowler/lib/outputs/html.py", line 22, in <module>
    from prowler.providers.azure.lib.audit_info.models import Azure_Audit_Info
  File "/opt/homebrew/Cellar/prowler/3.11.0/libexec/lib/python3.12/site-packages/prowler/providers/azure/lib/audit_info/models.py", line 4, in <module>
    from azure.identity import DefaultAzureCredential
  File "/opt/homebrew/Cellar/prowler/3.11.0/libexec/lib/python3.12/site-packages/azure/identity/__init__.py", line 10, in <module>
    from ._credentials import (
  File "/opt/homebrew/Cellar/prowler/3.11.0/libexec/lib/python3.12/site-packages/azure/identity/_credentials/__init__.py", line 5, in <module>
    from .authorization_code import AuthorizationCodeCredential
  File "/opt/homebrew/Cellar/prowler/3.11.0/libexec/lib/python3.12/site-packages/azure/identity/_credentials/authorization_code.py", line 9, in <module>
    from .._internal.aad_client import AadClient
  File "/opt/homebrew/Cellar/prowler/3.11.0/libexec/lib/python3.12/site-packages/azure/identity/_internal/__init__.py", line 5, in <module>
    from .aad_client import AadClient
  File "/opt/homebrew/Cellar/prowler/3.11.0/libexec/lib/python3.12/site-packages/azure/identity/_internal/aad_client.py", line 11, in <module>
    from .aad_client_base import AadClientBase
  File "/opt/homebrew/Cellar/prowler/3.11.0/libexec/lib/python3.12/site-packages/azure/identity/_internal/aad_client_base.py", line 20, in <module>
    from .aadclient_certificate import AadClientCertificate
  File "/opt/homebrew/Cellar/prowler/3.11.0/libexec/lib/python3.12/site-packages/azure/identity/_internal/aadclient_certificate.py", line 7, in <module>
    from cryptography import x509
  File "/opt/homebrew/opt/python-cryptography/lib/python3.12/site-packages/cryptography/x509/__init__.py", line 7, in <module>
    from cryptography.x509 import certificate_transparency
  File "/opt/homebrew/opt/python-cryptography/lib/python3.12/site-packages/cryptography/x509/certificate_transparency.py", line 11, in <module>
    from cryptography.hazmat.bindings._rust import x509 as rust_x509
pyo3_runtime.PanicException: Python API call failed
```
### How did you install Prowler?

From brew (brew install prowler)

### Environment Resource

Workstation

### OS used

MacOS

### Prowler version

3.11.0

### Pip version

23.2.1

### Context

It seems that the errors is caused by python3.11 the prowler used

**Comment by jfagoagas** [comment]
Hi @ripperi8u, I think there is something wrong in your environment because your Python virtual environment is using Python 3.11 but the Python libraries you are using are within the Python 3.12 folder. Can you check that? Prowler now supports Python up to 3.11.

**Comment by GohEeEn** [comment]
Hey @jfagoagas, I have the similar issue when I install prowler with `brew` too. I have tried reinstallation but it remains the same. So I am not sure if there is any issue with installation through `brew` or something ?
I got the similar error when I execute the `prowler --version` command too.

```
/usr/local/Cellar/prowler/3.11.1/libexec/lib/python3.12/site-packages/prowler/lib/banner.py:15: SyntaxWarning: invalid escape sequence '\|'
  """
Traceback (most recent call last):
  File "/usr/local/bin/prowler", line 5, in <module>
    from prowler.__main__ import prowler
  File "/usr/local/Cellar/prowler/3.11.1/libexec/lib/python3.12/site-packages/prowler/__main__.py", line 10, in <module>
    from prowler.lib.check.check import (
  File "/usr/local/Cellar/prowler/3.11.1/libexec/lib/python3.12/site-packages/prowler/lib/check/check.py", line 21, in <module>
    from prowler.lib.outputs.outputs import report
  File "/usr/local/Cellar/prowler/3.11.1/libexec/lib/python3.12/site-packages/prowler/lib/outputs/outputs.py", line 7, in <module>
    from prowler.lib.outputs.compliance import add_manual_controls, fill_compliance
  File "/usr/local/Cellar/prowler/3.11.1/libexec/lib/python3.12/site-packages/prowler/lib/outputs/compliance.py", line 5, in <module>
    from tabulate import tabulate
ModuleNotFoundError: No module named 'tabulate'
```

**Comment by jfagoagas** [comment]
Hi @GohEeEn, would you mind telling me how can I reproduce the issue step-by-step?

Thanks!

**Comment by GohEeEn** [comment]
Hi @jfagoagas, all I did is executing the command `brew install prowler` to install Prowler. It seems that Python@3.12 is listed as one of the dependencies through **homebrew** installation method, which is opposite of what you said for supporting up to Python3.11. Hence, I believe that is why we have python using the Python3.12 folder.

![image](https://github.com/prowler-cloud/prowler/assets/34720382/e823c8c6-482b-4623-b3d9-d20530550509)

**Comment by jfagoagas** [comment]
Hi @ripperi8u @GohEeEn I've just installed Prowler through brew with `brew install prowler` and is working fine:
<img width="1326" alt="Screenshot 2023-11-20 at 11 44 53" src="https://github.com/prowler-cloud/prowler/assets/16007882/39015bca-41be-4811-b994-b6528264f1cf">

I've manually aborted the execution since it was working fine.

Also there is no issue with the `-v/--version`. My bet is that some of the dependencies are not present in your system.
<img width="568" alt="Screenshot 2023-11-20 at 11 46 48" src="https://github.com/prowler-cloud/prowler/assets/16007882/e0b9220c-748f-4dee-8399-5e874db1e7b3">

Could you please install and execute it again using the latest version?

**Comment by ripperi8u** [comment]
> Hi @ripperi8u @GohEeEn I've just installed Prowler through brew with `brew install prowler` and is working fine: <img alt="Screenshot 2023-11-20 at 11 44 53" width="1326" src="https://user-images.githubusercontent.com/16007882/284240551-39015bca-41be-4811-b994-b6528264f1cf.png">
> 
> I've manually aborted the execution since it was working fine.
> 
> Also there is no issue with the `-v/--version`. My bet is that some of the dependencies are not present in your system. <img alt="Screenshot 2023-11-20 at 11 46 48" width="568" src="https://user-images.githubusercontent.com/16007882/284240789-e0b9220c-748f-4dee-8399-5e874db1e7b3.png">
> 
> Could you please install and execute it again using the latest version?

I update to the lastest version 3.11.3, and it works

**Comment by jfagoagas** [comment]
That's great @ripperi8u !! 

Thanks for using Prowler 🚀
