### ISSUE TITLE
[Bug]: Prowler 4.0.1 - ModuleNotFoundError: No module named 'resource'

### ISSUE THREAD

**Issue by pjhavariotis** [toniblyx/prowler#3737]
### Steps to Reproduce

I have just updated prowler to the latest version (4.0.1) and since then I'm getting the following error:
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\p.chavariotis\AppData\Local\Programs\Python\Python311\Scripts\prowler.exe\__main__.py", line 4, in <module>
  File "C:\Users\p.chavariotis\AppData\Local\Programs\Python\Python311\Lib\site-packages\prowler\__main__.py", line 11, in <module>
    from prowler.lib.check.check import (
  File "C:\Users\p.chavariotis\AppData\Local\Programs\Python\Python311\Lib\site-packages\prowler\lib\check\check.py", line 10, in <module>
    from resource import setrlimit
ModuleNotFoundError: No module named 'resource'
```

### Expected behavior

After installing the latest update, I cannot use the software anymore. With the previously installed version (3.16.0), this issue was not there!

### Actual Result with Screenshots or Logs

N/A

### How did you install Prowler?

Cloning the repository from github.com (git clone)

### Environment Resource

7. Windows Workstation

### OS used

4. Windows 10

### Prowler version

Prowler 4.0.1

### Pip version

pip 24.0

**Comment by MrCloudSec** [comment]
Hi @pjhavariotis , good catch! Thanks for reaching us out, the PR with the fix will be merged soon.
Thanks for using Prowler 🚀
