### ISSUE TITLE
[Bug]: Encoding issue with Dashboard on Prowler 4.1.0 - Aces High

### ISSUE THREAD

**Issue by irboi746** [toniblyx/prowler#3866]
### Steps to Reproduce

After running the scan, there is an encoding error when trying to open the dashboard using `python prowler.py dashboard`

The error is as below:

```
Traceback (most recent call last):
  File "C:\Users\Test\Desktop\prowler-4.1.0\prowler.py", line 7, in <module>
    sys.exit(prowler())
  File "C:\Users\Test\Desktop\prowler-4.1.0\prowler\__main__.py", line 64, in prowler
    from dashboard.__main__ import dashboard
  File "C:\Users\Test\Desktop\prowler-4.1.0\dashboard\__main__.py", line 28, in <module>
    dashboard = dash.Dash(
  File "C:\Users\Test\AppData\Local\pypoetry\Cache\virtualenvs\prowler-SRE5BNE--py3.10\lib\site-packages\dash\dash.py", line 545, in __init__
    self.init_app()
  File "C:\Users\Test\AppData\Local\pypoetry\Cache\virtualenvs\prowler-SRE5BNE--py3.10\lib\site-packages\dash\dash.py", line 623, in init_app
    self.enable_pages()
  File "C:\Users\Test\AppData\Local\pypoetry\Cache\virtualenvs\prowler-SRE5BNE--py3.10\lib\site-packages\dash\dash.py", line 2130, in enable_pages
    _import_layouts_from_pages(self.config.pages_folder)
  File "C:\Users\Test\AppData\Local\pypoetry\Cache\virtualenvs\prowler-SRE5BNE--py3.10\lib\site-packages\dash\_pages.py", line 435, in _import_layouts_from_pages
    spec.loader.exec_module(page_module)
  File "C:\Users\Test\Desktop\prowler-4.1.0\dashboard\pages\compliance.py", line 43, in <module>
    num_rows = sum(1 for row in reader)
  File "C:\Users\Test\Desktop\prowler-4.1.0\dashboard\pages\compliance.py", line 43, in <genexpr>
    num_rows = sum(1 for row in reader)
  File "C:\Python310\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x92 in position 5171: invalid start byte
```

When attempting to change `encoding_format` in `\prowler-4.1.0\dashboard\config.py` from `utf-8` to `windows-1252` or ` ISO-88659-1` we will get a new error as follows:

```
Traceback (most recent call last):
  File "C:\Users\Test\Desktop\prowler-4.1.0\prowler.py", line 7, in <module>
    sys.exit(prowler())
  File "C:\Users\Test\Desktop\prowler-4.1.0\prowler\__main__.py", line 64, in prowler
    from dashboard.__main__ import dashboard
  File "C:\Users\Test\Desktop\prowler-4.1.0\dashboard\__main__.py", line 28, in <module>
    dashboard = dash.Dash(
  File "C:\Users\Test\AppData\Local\pypoetry\Cache\virtualenvs\prowler-SRE5BNE--py3.10\lib\site-packages\dash\dash.py", line 545, in __init__
    self.init_app()
  File "C:\Users\Test\AppData\Local\pypoetry\Cache\virtualenvs\prowler-SRE5BNE--py3.10\lib\site-packages\dash\dash.py", line 623, in init_app
    self.enable_pages()
  File "C:\Users\Test\AppData\Local\pypoetry\Cache\virtualenvs\prowler-SRE5BNE--py3.10\lib\site-packages\dash\dash.py", line 2130, in enable_pages
    _import_layouts_from_pages(self.config.pages_folder)
  File "C:\Users\Test\AppData\Local\pypoetry\Cache\virtualenvs\prowler-SRE5BNE--py3.10\lib\site-packages\dash\_pages.py", line 435, in _import_layouts_from_pages
    spec.loader.exec_module(page_module)
  File "C:\Users\Test\Desktop\prowler-4.1.0\dashboard\pages\overview.py", line 92, in <module>
    data = load_csv_files(csv_files)
  File "C:\Users\Test\Desktop\prowler-4.1.0\dashboard\pages\overview.py", line 80, in load_csv_files
    df = pd.read_csv(file, sep=";", on_bad_lines="skip")
  File "C:\Users\Test\AppData\Local\pypoetry\Cache\virtualenvs\prowler-SRE5BNE--py3.10\lib\site-packages\pandas\io\parsers\readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "C:\Users\Test\AppData\Local\pypoetry\Cache\virtualenvs\prowler-SRE5BNE--py3.10\lib\site-packages\pandas\io\parsers\readers.py", line 626, in _read
    return parser.read(nrows)
  File "C:\Users\Test\AppData\Local\pypoetry\Cache\virtualenvs\prowler-SRE5BNE--py3.10\lib\site-packages\pandas\io\parsers\readers.py", line 1923, in read
    ) = self._engine.read(  # type: ignore[attr-defined]
  File "C:\Users\Test\AppData\Local\pypoetry\Cache\virtualenvs\prowler-SRE5BNE--py3.10\lib\site-packages\pandas\io\parsers\c_parser_wrapper.py", line 234, in read
    chunks = self._reader.read_low_memory(nrows)
  File "parsers.pyx", line 838, in pandas._libs.parsers.TextReader.read_low_memory
  File "parsers.pyx", line 905, in pandas._libs.parsers.TextReader._read_rows
  File "parsers.pyx", line 874, in pandas._libs.parsers.TextReader._tokenize_rows
  File "parsers.pyx", line 891, in pandas._libs.parsers.TextReader._check_tokenize_status
  File "parsers.pyx", line 2053, in pandas._libs.parsers.raise_parser_error
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x97 in position 175279: invalid start byte
```

### Expected behavior

Dashboard should be running 

### Actual Result with Screenshots or Logs

First Error

```
Traceback (most recent call last):
  File "C:\Users\Test\Desktop\prowler-4.1.0\prowler.py", line 7, in <module>
    sys.exit(prowler())
  File "C:\Users\Test\Desktop\prowler-4.1.0\prowler\__main__.py", line 64, in prowler
    from dashboard.__main__ import dashboard
  File "C:\Users\Test\Desktop\prowler-4.1.0\dashboard\__main__.py", line 28, in <module>
    dashboard = dash.Dash(
  File "C:\Users\Test\AppData\Local\pypoetry\Cache\virtualenvs\prowler-SRE5BNE--py3.10\lib\site-packages\dash\dash.py", line 545, in __init__
    self.init_app()
  File "C:\Users\Test\AppData\Local\pypoetry\Cache\virtualenvs\prowler-SRE5BNE--py3.10\lib\site-packages\dash\dash.py", line 623, in init_app
    self.enable_pages()
  File "C:\Users\Test\AppData\Local\pypoetry\Cache\virtualenvs\prowler-SRE5BNE--py3.10\lib\site-packages\dash\dash.py", line 2130, in enable_pages
    _import_layouts_from_pages(self.config.pages_folder)
  File "C:\Users\Test\AppData\Local\pypoetry\Cache\virtualenvs\prowler-SRE5BNE--py3.10\lib\site-packages\dash\_pages.py", line 435, in _import_layouts_from_pages
    spec.loader.exec_module(page_module)
  File "C:\Users\Test\Desktop\prowler-4.1.0\dashboard\pages\compliance.py", line 43, in <module>
    num_rows = sum(1 for row in reader)
  File "C:\Users\Test\Desktop\prowler-4.1.0\dashboard\pages\compliance.py", line 43, in <genexpr>
    num_rows = sum(1 for row in reader)
  File "C:\Python310\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x92 in position 5171: invalid start byte
```

Second Error

```
Traceback (most recent call last):
  File "C:\Users\Test\Desktop\prowler-4.1.0\prowler.py", line 7, in <module>
    sys.exit(prowler())
  File "C:\Users\Test\Desktop\prowler-4.1.0\prowler\__main__.py", line 64, in prowler
    from dashboard.__main__ import dashboard
  File "C:\Users\Test\Desktop\prowler-4.1.0\dashboard\__main__.py", line 28, in <module>
    dashboard = dash.Dash(
  File "C:\Users\Test\AppData\Local\pypoetry\Cache\virtualenvs\prowler-SRE5BNE--py3.10\lib\site-packages\dash\dash.py", line 545, in __init__
    self.init_app()
  File "C:\Users\Test\AppData\Local\pypoetry\Cache\virtualenvs\prowler-SRE5BNE--py3.10\lib\site-packages\dash\dash.py", line 623, in init_app
    self.enable_pages()
  File "C:\Users\Test\AppData\Local\pypoetry\Cache\virtualenvs\prowler-SRE5BNE--py3.10\lib\site-packages\dash\dash.py", line 2130, in enable_pages
    _import_layouts_from_pages(self.config.pages_folder)
  File "C:\Users\Test\AppData\Local\pypoetry\Cache\virtualenvs\prowler-SRE5BNE--py3.10\lib\site-packages\dash\_pages.py", line 435, in _import_layouts_from_pages
    spec.loader.exec_module(page_module)
  File "C:\Users\Test\Desktop\prowler-4.1.0\dashboard\pages\overview.py", line 92, in <module>
    data = load_csv_files(csv_files)
  File "C:\Users\Test\Desktop\prowler-4.1.0\dashboard\pages\overview.py", line 80, in load_csv_files
    df = pd.read_csv(file, sep=";", on_bad_lines="skip")
  File "C:\Users\Test\AppData\Local\pypoetry\Cache\virtualenvs\prowler-SRE5BNE--py3.10\lib\site-packages\pandas\io\parsers\readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "C:\Users\Test\AppData\Local\pypoetry\Cache\virtualenvs\prowler-SRE5BNE--py3.10\lib\site-packages\pandas\io\parsers\readers.py", line 626, in _read
    return parser.read(nrows)
  File "C:\Users\Test\AppData\Local\pypoetry\Cache\virtualenvs\prowler-SRE5BNE--py3.10\lib\site-packages\pandas\io\parsers\readers.py", line 1923, in read
    ) = self._engine.read(  # type: ignore[attr-defined]
  File "C:\Users\Test\AppData\Local\pypoetry\Cache\virtualenvs\prowler-SRE5BNE--py3.10\lib\site-packages\pandas\io\parsers\c_parser_wrapper.py", line 234, in read
    chunks = self._reader.read_low_memory(nrows)
  File "parsers.pyx", line 838, in pandas._libs.parsers.TextReader.read_low_memory
  File "parsers.pyx", line 905, in pandas._libs.parsers.TextReader._read_rows
  File "parsers.pyx", line 874, in pandas._libs.parsers.TextReader._tokenize_rows
  File "parsers.pyx", line 891, in pandas._libs.parsers.TextReader._check_tokenize_status
  File "parsers.pyx", line 2053, in pandas._libs.parsers.raise_parser_error
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x97 in position 175279: invalid start byte
```

### How did you install Prowler?

Cloning the repository from github.com (git clone)

### Environment Resource

Running on workstation.

### OS used

Windows 10
Kali Linux (attempting to parse output from windows 10 in Kali Linux gives the same error.)

### Prowler version

4.1.0

### Pip version

pip 24.0

### Context

In an attempt for a quick fix, I have changed the following areas with some success. 

Firstly, change `encoding_format` in `\prowler-4.1.0\dashboard\config.py` from `utf-8` to `windows-1252` or ` ISO-88659-1`

Initial:

```
# Encoding
encoding_format = "utf-8"
```

Quick Fixed: 

```
# Encoding
encoding_format = "windows-1252"
```

Next add `encoding='unicode_escape'` to `df = pd.read_csv()` line in function `def load_csv_files(csv_files)` in `\prowler-4.1.0\dashboard\pages\overview.py`

Initial : 
```
def load_csv_files(csv_files):
    """Load CSV files into a single pandas DataFrame."""
    dfs = []
    for file in csv_files:
        df = pd.read_csv(file, sep=";", on_bad_lines="skip")
```

Quick Fixed: 
```
def load_csv_files(csv_files):
    """Load CSV files into a single pandas DataFrame."""
    dfs = []
    for file in csv_files:
        df = pd.read_csv(file, sep=";", on_bad_lines="skip",encoding='unicode_escape')
        if "CHECK_ID" in df.columns:
```

**Comment by pedrooot** [comment]
Hi @irboi746 thanks for the report. We found a solution for this issue but it's still in review because we are evaluating the best approach. In [this pr](https://github.com/prowler-cloud/prowler/pull/3847) you can find the current solution. Tell me if it works for you please!!
Thanks for using Prowler! 🚀

**Comment by sh3llcmdr** [comment]
I had the same issue and the [pr](https://github.com/prowler-cloud/prowler/pull/3847) you linked to has fixed the issue for me. Thanks

**Comment by mishradhananjai117** [comment]
in My case still I am stuck after the suggested change.

**First Changes** 

encoding_format = "windows-1252"

**Second Changes** 

def load_csv_files(csv_files):
    """Load CSV files into a single pandas DataFrame."""
    dfs = []
    for file in csv_files:
        df = pd.read_csv(file, sep=";", on_bad_lines="skip",encoding='unicode_escape')
        if "CHECK_ID" in df.columns:
            if "TIMESTAMP" in df.columns or df["PROVIDER"].unique() == "aws":
                dfs.append(df.astype(str))


**Result** 
Loading all CSV files from the folder C:\Users\Dhananjai Mishra/output ...

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Dhananjai Mishra\AppData\Local\Programs\Python\Python312\Scripts\prowler.exe\__main__.py", line 7, in <module>
  File "C:\Users\Dhananjai Mishra\AppData\Local\Programs\Python\Python312\Lib\site-packages\prowler\__main__.py", line 64, in prowler
    from dashboard.__main__ import dashboard
  File "C:\Users\Dhananjai Mishra\AppData\Local\Programs\Python\Python312\Lib\site-packages\dashboard\__main__.py", line 28, in <module>
    dashboard = dash.Dash(
                ^^^^^^^^^^
  File "C:\Users\Dhananjai Mishra\AppData\Local\Programs\Python\Python312\Lib\site-packages\dash\dash.py", line 545, in __init__
    self.init_app()
  File "C:\Users\Dhananjai Mishra\AppData\Local\Programs\Python\Python312\Lib\site-packages\dash\dash.py", line 623, in init_app
    self.enable_pages()
  File "C:\Users\Dhananjai Mishra\AppData\Local\Programs\Python\Python312\Lib\site-packages\dash\dash.py", line 2130, in enable_pages
    _import_layouts_from_pages(self.config.pages_folder)
  File "C:\Users\Dhananjai Mishra\AppData\Local\Programs\Python\Python312\Lib\site-packages\dash\_pages.py", line 435, in _import_layouts_from_pages
    spec.loader.exec_module(page_module)
  File "C:\Users\Dhananjai Mishra\AppData\Local\Programs\Python\Python312\Lib\site-packages\dashboard\pages\compliance.py", line 96, in <module>
    data, results = load_csv_files(csv_files)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhananjai Mishra\AppData\Local\Programs\Python\Python312\Lib\site-packages\dashboard\pages\compliance.py", line 53, in load_csv_files
    df = pd.read_csv(file, sep=";", on_bad_lines="skip")
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhananjai Mishra\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\io\parsers\readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhananjai Mishra\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\io\parsers\readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhananjai Mishra\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\io\parsers\readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhananjai Mishra\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\io\parsers\readers.py", line 1898, in _make_engine
    return mapping[engine](f, **self.options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhananjai Mishra\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\io\parsers\c_parser_wrapper.py", line 93, in __init__
    self._reader = parsers.TextReader(src, **kwds)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "parsers.pyx", line 574, in pandas._libs.parsers.TextReader.__cinit__
  File "parsers.pyx", line 663, in pandas._libs.parsers.TextReader._get_header
  File "parsers.pyx", line 874, in pandas._libs.parsers.TextReader._tokenize_rows
  File "parsers.pyx", line 891, in pandas._libs.parsers.TextReader._check_tokenize_status
  File "parsers.pyx", line 2053, in pandas._libs.parsers.raise_parser_error
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x92 in position 5171: invalid start byte

**Comment by pedrooot** [comment]
Hey! @mishradhananjai117 this can be happpening because you are still using an older version or the output folder has old files with incorrect format. To ensure everything is ok you can make these comprobations:
* Clone the last version of Prowler from github, the dashboard encoding fix is not released in pip at the moment (will be released soon)
* Ensure that the output folder hasn't old outputs with bad enconding. I would delete this folder, generate the new files with the latest version of Prowler and run the dashboard.

If after all the steps you are still getting errors, we will investigate furthermore. Thanks for using Prowler!! 🚀

**Comment by JosephRojas01** [comment]
Hi!
Since the last update with dashboard encoding fix is not currently available with pip, I made the changes included in this [pull](https://github.com/prowler-cloud/prowler/pull/3847), in addition I delete all old outputs, but now I have the following error

```
C:\Users\test\Documents\github\prowler>prowler dashboard
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\test\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\Scripts\prowler.exe\__main__.py", line 4, in <module>
  File "C:\Users\test\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\prowler\__main__.py", line 11, in <module>
    from prowler.lib.check.check import (
  File "C:\Users\test\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\prowler\lib\check\check.py", line 18, in <module>
    from prowler.lib.check.compliance_models import load_compliance_framework
  File "C:\Users\test\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\prowler\lib\check\compliance_models.py", line 80, in <module>
    class CIS_Requirement_Attribute(BaseModel):
  File "C:\Users\test\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pydantic\_internal\_model_construction.py", line 202, in __new__
    complete_model_class(
  File "C:\Users\test\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pydantic\_internal\_model_construction.py", line 539, in complete_model_class
    schema = cls.__get_pydantic_core_schema__(cls, handler)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\test\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pydantic\main.py", line 626, in __get_pydantic_core_schema__
    return handler(source)
           ^^^^^^^^^^^^^^^
  File "C:\Users\test\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pydantic\_internal\_schema_generation_shared.py", line 82, in __call__
    schema = self._handler(source_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\test\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pydantic\_internal\_generate_schema.py", line 502, in generate_schema
    schema = self._generate_schema_inner(obj)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\test\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pydantic\_internal\_generate_schema.py", line 753, in _generate_schema_inner
    return self._model_schema(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\test\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pydantic\_internal\_generate_schema.py", line 580, in _model_schema
    {k: self._generate_md_field_schema(k, v, decorators) for k, v in fields.items()},
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\test\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pydantic\_internal\_generate_schema.py", line 580, in <dictcomp>
    {k: self._generate_md_field_schema(k, v, decorators) for k, v in fields.items()},
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\test\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pydantic\_internal\_generate_schema.py", line 916, in _generate_md_field_schema
    common_field = self._common_field_schema(name, field_info, decorators)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\test\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pydantic\_internal\_generate_schema.py", line 1081, in _common_field_schema
    schema = self._apply_annotations(
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\test\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pydantic\_internal\_generate_schema.py", line 1820, in _apply_annotations
    schema = get_inner_schema(source_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\test\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pydantic\_internal\_schema_generation_shared.py", line 82, in __call__
    schema = self._handler(source_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\test\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pydantic\_internal\_generate_schema.py", line 1801, in inner_handler
    schema = self._generate_schema_inner(obj)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\test\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pydantic\_internal\_generate_schema.py", line 758, in _generate_schema_inner
    return self.match_type(obj)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\test\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pydantic\_internal\_generate_schema.py", line 844, in match_type
    return self._unknown_type_schema(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\test\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pydantic\_internal\_generate_schema.py", line 405, in _unknown_type_schema
    raise PydanticSchemaGenerationError(
pydantic.errors.PydanticSchemaGenerationError: Unable to generate pydantic-core schema for <class 'prowler.lib.check.compliance_models.CIS_Requirement_Attribute_Profile'>. Set `arbitrary_types_allowed=True` in the model_config to ignore this error or implement `__get_pydantic_core_schema__` on your type to fully support it.

If you got this error by calling handler(<some type>) within `__get_pydantic_core_schema__` then you likely need to call `handler.generate_schema(<some type>)` since we do not call `__get_pydantic_core_schema__` on `<some type>` otherwise to avoid infinite recursion.

For further information visit https://errors.pydantic.dev/2.7/u/schema-for-unknown-type
```

## Expected behavior

Dashboard should be running

## Actual Result with Screenshots or Logs
```
C:\Users\test\Documents\github\prowler>prowler dashboard
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\test\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\Scripts\prowler.exe\__main__.py", line 4, in <module>
  File "C:\Users\test\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\prowler\__main__.py", line 11, in <module>
    from prowler.lib.check.check import (
  File "C:\Users\test\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\prowler\lib\check\check.py", line 18, in <module>
    from prowler.lib.check.compliance_models import load_compliance_framework
  File "C:\Users\test\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\prowler\lib\check\compliance_models.py", line 80, in <module>
    class CIS_Requirement_Attribute(BaseModel):
  File "C:\Users\test\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pydantic\_internal\_model_construction.py", line 202, in __new__
    complete_model_class(
  File "C:\Users\test\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pydantic\_internal\_model_construction.py", line 539, in complete_model_class
    schema = cls.__get_pydantic_core_schema__(cls, handler)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\test\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pydantic\main.py", line 626, in __get_pydantic_core_schema__
    return handler(source)
           ^^^^^^^^^^^^^^^
  File "C:\Users\test\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pydantic\_internal\_schema_generation_shared.py", line 82, in __call__
    schema = self._handler(source_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\test\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pydantic\_internal\_generate_schema.py", line 502, in generate_schema
    schema = self._generate_schema_inner(obj)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\test\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pydantic\_internal\_generate_schema.py", line 753, in _generate_schema_inner
    return self._model_schema(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\test\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pydantic\_internal\_generate_schema.py", line 580, in _model_schema
    {k: self._generate_md_field_schema(k, v, decorators) for k, v in fields.items()},
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\test\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pydantic\_internal\_generate_schema.py", line 580, in <dictcomp>
    {k: self._generate_md_field_schema(k, v, decorators) for k, v in fields.items()},
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\test\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pydantic\_internal\_generate_schema.py", line 916, in _generate_md_field_schema
    common_field = self._common_field_schema(name, field_info, decorators)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\test\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pydantic\_internal\_generate_schema.py", line 1081, in _common_field_schema
    schema = self._apply_annotations(
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\test\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pydantic\_internal\_generate_schema.py", line 1820, in _apply_annotations
    schema = get_inner_schema(source_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\test\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pydantic\_internal\_schema_generation_shared.py", line 82, in __call__
    schema = self._handler(source_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\test\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pydantic\_internal\_generate_schema.py", line 1801, in inner_handler
    schema = self._generate_schema_inner(obj)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\test\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pydantic\_internal\_generate_schema.py", line 758, in _generate_schema_inner
    return self.match_type(obj)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\test\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pydantic\_internal\_generate_schema.py", line 844, in match_type
    return self._unknown_type_schema(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\test\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pydantic\_internal\_generate_schema.py", line 405, in _unknown_type_schema
    raise PydanticSchemaGenerationError(
pydantic.errors.PydanticSchemaGenerationError: Unable to generate pydantic-core schema for <class 'prowler.lib.check.compliance_models.CIS_Requirement_Attribute_Profile'>. Set `arbitrary_types_allowed=True` in the model_config to ignore this error or implement `__get_pydantic_core_schema__` on your type to fully support it.

If you got this error by calling handler(<some type>) within `__get_pydantic_core_schema__` then you likely need to call `handler.generate_schema(<some type>)` since we do not call `__get_pydantic_core_schema__` on `<some type>` otherwise to avoid infinite recursion.

For further information visit https://errors.pydantic.dev/2.7/u/schema-for-unknown-type
```

## How did you install Prowler?

Using pip `pip install prowler`

## OS used
Windows 10

## Prowler version
4.1.0

## Pip version
pip 23.3.2

**Comment by pedrooot** [comment]
Hi! @JosephRojas01 the pr you are referring it's an old approach of the solution. Currently, on `master` we fixed this issue. We are releasing this fix soon so you will be able to fix it from the pip installation, meanwhile you can pull the latest changes from `master`. Tell me if smthg doesn't work for you and we will investigater futhermore (don't hesitate to re-open this issue). Thanks for using Prowler!!
