### ISSUE TITLE
Time format changed between 4.2.4 and 4.3?

### ISSUE THREAD

**Issue by woodyweaver** [toniblyx/prowler#4621]
### Steps to Reproduce

export HOST=0.0.0.0; nohup prowler dashboard > ~/prowler.out 2>~/prowler.err &

### Expected behavior

Dashboard comes up

### Actual Result with Screenshots or Logs

```
Traceback (most recent call last):
  File "/home/weaverw/.local/bin/prowler", line 8, in <module>
    sys.exit(prowler())
  File "/home/weaverw/.local/lib/python3.9/site-packages/prowler/__main__.py", line 85, in prowler
    from dashboard.__main__ import dashboard
  File "/home/weaverw/.local/lib/python3.9/site-packages/dashboard/__main__.py", line 28, in <module>
    dashboard = dash.Dash(
  File "/home/weaverw/.local/lib/python3.9/site-packages/dash/dash.py", line 551, in __init__
    self.init_app()
  File "/home/weaverw/.local/lib/python3.9/site-packages/dash/dash.py", line 630, in init_app
    self.enable_pages()
  File "/home/weaverw/.local/lib/python3.9/site-packages/dash/dash.py", line 2184, in enable_pages
    _import_layouts_from_pages(self.config.pages_folder)
  File "/home/weaverw/.local/lib/python3.9/site-packages/dash/_pages.py", line 444, in _import_layouts_from_pages
    spec.loader.exec_module(page_module)
  File "/home/weaverw/.local/lib/python3.9/site-packages/dashboard/pages/compliance.py", line 127, in <module>
    data["ASSESSMENTDATE"] = pd.to_datetime(data["ASSESSMENTDATE"])
  File "/home/weaverw/.local/lib/python3.9/site-packages/pandas/core/tools/datetimes.py", line 1063, in to_datetime
    cache_array = _maybe_cache(arg, format, cache, convert_listlike)
  File "/home/weaverw/.local/lib/python3.9/site-packages/pandas/core/tools/datetimes.py", line 247, in _maybe_cache
    cache_dates = convert_listlike(unique_dates, format)
  File "/home/weaverw/.local/lib/python3.9/site-packages/pandas/core/tools/datetimes.py", line 433, in _convert_listlike_datetimes
    return _array_strptime_with_fallback(arg, name, utc, format, exact, errors)
  File "/home/weaverw/.local/lib/python3.9/site-packages/pandas/core/tools/datetimes.py", line 467, in _array_strptime_with_fallback
    result, tz_out = array_strptime(arg, fmt, exact=exact, errors=errors, utc=utc)
  File "strptime.pyx", line 501, in pandas._libs.tslibs.strptime.array_strptime
  File "strptime.pyx", line 451, in pandas._libs.tslibs.strptime.array_strptime
  File "strptime.pyx", line 583, in pandas._libs.tslibs.strptime._parse_with_format
ValueError: time data "2024-07-30T17:21:41.983099" doesn't match format "%Y-%m-%d %H:%M:%S.%f", at position 1. You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.

```

### How did you install Prowler?

From pip package (pip install prowler)

### Environment Resource

EC2 instance

### OS used

Red Hat Enterprise Linux release 9.4 (Plow)

### Prowler version

Prowler 4.3.1 (You are running the latest version, yay!)

### Pip version

pip 21.2.3 from /usr/lib/python3.9/site-packages/pip (python 3.9)

### Context

Working normally (from laptop) with version 4.2.2, 4.2.4.  Installed on EC2 instance, and it broke.  Can confirm that the CSV has the (same) time format "%Y-%m-%dT%H:%M:%S.%f"

**Comment by pedrooot** [comment]
Hey! @woodyweaver thanks for this report, we will review this with the team, and we'll get back to you soon.
Thanks for using Prowler! 🚀

**Comment by pedrooot** [comment]
Hi! @woodyweaver I'm trying to replicate this issue but it worked for me, could you please share with me the full log of the execution? It would be really useful to make the triage of this issue 😄

**Comment by woodyweaver** [comment]
Hi, @pedrooot -- not sure what to say.  I prepare for this I did a pip uninstall and pip install.  Ran the same scripts.  And this time, it's not providing the T in the CSV files, they are all correctly using a space delimiter.  So apparently it was just on that 7/30 run, a one-off.  Not reproducible, go ahead and close the ticket.

**Comment by pedrooot** [comment]
Nice to read that now you can use Prowler dashboards. If you need anything else just tell me!

**Comment by guidorugo** [comment]
Sorry, but I have the issue, even after uninstall and install. 

Upgraded from 4.3.0 to 4.3.2. Running on Mac Sonoma 14.4.1/
pip 24.2 from /Users/guido.rugo/Library/Python/3.9/lib/python/site-packages/pip (python 3.9)

```
❯ prowler dashboard
/Users/guido.rugo/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
                         _
 _ __  _ __ _____      _| | ___ _ __
| '_ \| '__/ _ \ \ /\ / / |/ _ \ '__|
| |_) | | | (_) \ V  V /| |  __/ |
| .__/|_|  \___/ \_/\_/ |_|\___|_|v4.3.2
|_| the handy multi-cloud security tool

Date: 2024-08-07 09:41:01

Loading all CSV files from the folder /Users/guido.rugo/output/output ...

Traceback (most recent call last):
  File "/Users/guido.rugo/Library/Python/3.9/bin/prowler", line 8, in <module>
    sys.exit(prowler())
  File "/Users/guido.rugo/Library/Python/3.9/lib/python/site-packages/prowler/__main__.py", line 85, in prowler
    from dashboard.__main__ import dashboard
  File "/Users/guido.rugo/Library/Python/3.9/lib/python/site-packages/dashboard/__main__.py", line 28, in <module>
    dashboard = dash.Dash(
  File "/Users/guido.rugo/Library/Python/3.9/lib/python/site-packages/dash/dash.py", line 551, in __init__
    self.init_app()
  File "/Users/guido.rugo/Library/Python/3.9/lib/python/site-packages/dash/dash.py", line 630, in init_app
    self.enable_pages()
  File "/Users/guido.rugo/Library/Python/3.9/lib/python/site-packages/dash/dash.py", line 2184, in enable_pages
    _import_layouts_from_pages(self.config.pages_folder)
  File "/Users/guido.rugo/Library/Python/3.9/lib/python/site-packages/dash/_pages.py", line 444, in _import_layouts_from_pages
    spec.loader.exec_module(page_module)
  File "/Users/guido.rugo/Library/Python/3.9/lib/python/site-packages/dashboard/pages/compliance.py", line 127, in <module>
    data["ASSESSMENTDATE"] = pd.to_datetime(data["ASSESSMENTDATE"])
  File "/Users/guido.rugo/Library/Python/3.9/lib/python/site-packages/pandas/core/tools/datetimes.py", line 1063, in to_datetime
    cache_array = _maybe_cache(arg, format, cache, convert_listlike)
  File "/Users/guido.rugo/Library/Python/3.9/lib/python/site-packages/pandas/core/tools/datetimes.py", line 247, in _maybe_cache
    cache_dates = convert_listlike(unique_dates, format)
  File "/Users/guido.rugo/Library/Python/3.9/lib/python/site-packages/pandas/core/tools/datetimes.py", line 433, in _convert_listlike_datetimes
    return _array_strptime_with_fallback(arg, name, utc, format, exact, errors)
  File "/Users/guido.rugo/Library/Python/3.9/lib/python/site-packages/pandas/core/tools/datetimes.py", line 467, in _array_strptime_with_fallback
    result, tz_out = array_strptime(arg, fmt, exact=exact, errors=errors, utc=utc)
  File "strptime.pyx", line 501, in pandas._libs.tslibs.strptime.array_strptime
  File "strptime.pyx", line 451, in pandas._libs.tslibs.strptime.array_strptime
  File "strptime.pyx", line 583, in pandas._libs.tslibs.strptime._parse_with_format
ValueError: time data "2024-08-06 12:54:25.591121" doesn't match format "%Y-%m-%dT%H:%M:%S.%f", at position 1. You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.
```

**Comment by pedrooot** [comment]
Hey! @guidorugo how are you? I'm checking this error right now and I'll ping you with a solution!

**Comment by pedrooot** [comment]
@guidorugo could you follow this steps to make sure that everything it's fine:
* Delete the output folder generated by prowler
* Re-run a prowler execution
* Run prowler dashboard
If the error persist or is solved just tell me!

**Comment by guidorugo** [comment]
> @guidorugo could you follow this steps to make sure that everything it's fine:
> 
> * Delete the output folder generated by prowler
> * Re-run a prowler execution
> * Run prowler dashboard
>   If the error persist or is solved just tell me!

Yeah, that worked. No delete was needed, I just moved the output folder.

**Comment by pedrooot** [comment]
Nice! 🔝

**Comment by shermanjoshua** [comment]
I had this problem too, but deleting the folder didn't fix. Then I remembered that I was using the standard bash shebang in my script that was pointed at `/usr/local/bin/bash` on my mac. I updated it to use a newer version of bash (homebrew - `/opt/homebrew/bin/bash`) and that fixed it.
