### ISSUE TITLE
No file output despite successful aws scan

### ISSUE THREAD

**Issue by iankyslytsya** [toniblyx/prowler#4655]
### Steps to Reproduce

1. Install prowler via pipx
2. Run prowler aws profile --
3. Python errors after successful scan
4. Output and compliance folders are created but 0 files in them.

### Expected behavior

I expect the default output files to be created for prowler aws.

### Actual Result with Screenshots or Logs

`Executing 383 checks, please wait...
-> Scan completed! |▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉| 383/383 [100%] in 7:10.3 
Traceback (most recent call last):
  File "/home/iankyslytsya/.local/bin/prowler", line 8, in <module>
    sys.exit(prowler())
             ^^^^^^^^^
  File "/home/iankyslytsya/.local/share/pipx/venvs/prowler/lib/python3.12/site-packages/prowler/__main__.py", line 306, in prowler
    Finding.generate_output(global_provider, finding) for finding in findings
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/iankyslytsya/.local/share/pipx/venvs/prowler/lib/python3.12/site-packages/prowler/lib/outputs/finding.py", line 106, in generate_output
    common_finding_data = fill_common_finding_data(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/iankyslytsya/.local/share/pipx/venvs/prowler/lib/python3.12/site-packages/prowler/lib/outputs/common.py", line 39, in fill_common_finding_data
    "resource_tags": unroll_tags(finding.resource_tags),
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/iankyslytsya/.local/share/pipx/venvs/prowler/lib/python3.12/site-packages/prowler/lib/outputs/utils.py", line 64, in unroll_tags
    if "key" in tags[0]:
                ~~~~^^^
KeyError: 0`

### How did you install Prowler?

From pip package (pip install prowler)

### Environment Resource

PC

### OS used

Ubuntu 24.04 LTS

### Prowler version

Prowler 4.3.2

### Pip version

pipx version is 1.4.3

### Context

After adding `print(tags)` before line 64, I get different tags such as:

`{'Deplyoment': 'Terraform', 'Environment': 'Test', 'Owner': 'developers-team', 'Project': 'Connector'}`

**Comment by jfagoagas** [comment]
Hello @iankyslytsya we've just merged the PR that fixes you issue to the `master` branch, we will release a PATCH version soon.

Thank you for using Prowler 🚀
