### ISSUE TITLE
Getting issue while running prowler aws in Windows

### ISSUE THREAD

**Issue by akshaypawar2508** [toniblyx/prowler#5295]
### Steps to Reproduce

1- prowler aws

### Expected behavior

The scan should shows the result of aws resources scanning result

### Actual Result with Screenshots or Logs

When i an running the prowler aws i am getting file not found error even after the file is present at the given location.

Error:

PS C:\Users\LP-11> prowler
                         _
 _ __  _ __ _____      _| | ___ _ __
| '_ \| '__/ _ \ \ /\ / / |/ _ \ '__|
| |_) | | | (_) \ V  V /| |  __/ |
| .__/|_|  \___/ \_/\_/ |_|\___|_|v4.4.0
|_| the handy multi-cloud security tool

Date: 2024-10-04 19:23:12

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\LP-11\AppData\Local\Programs\Python\Python312\Scripts\prowler.exe\__main__.py", line 7, in <module>
  File "C:\Users\LP-11\AppData\Local\Programs\Python\Python312\Lib\site-packages\prowler\__main__.py", line 139, in prowler
    bulk_checks_metadata = CheckMetadata.get_bulk(provider)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LP-11\AppData\Local\Programs\Python\Python312\Lib\site-packages\prowler\lib\check\models.py", line 156, in get_bulk
    check_metadata = load_check_metadata(metadata_file)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LP-11\AppData\Local\Programs\Python\Python312\Lib\site-packages\prowler\lib\check\models.py", line 286, in load_check_metadata
    check_metadata = CheckMetadata.parse_file(metadata_file)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LP-11\AppData\Local\Programs\Python\Python312\Lib\site-packages\pydantic\main.py", line 561, in parse_file
    obj = load_file(
          ^^^^^^^^^^
  File "C:\Users\LP-11\AppData\Local\Programs\Python\Python312\Lib\site-packages\pydantic\parse.py", line 57, in load_file
    b = path.read_bytes()
        ^^^^^^^^^^^^^^^^^
  File "C:\Users\LP-11\AppData\Local\Programs\Python\Python312\Lib\pathlib.py", line 1019, in read_bytes
    with self.open(mode='rb') as f:
         ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LP-11\AppData\Local\Programs\Python\Python312\Lib\pathlib.py", line 1013, in open
    return io.open(self, mode, buffering, encoding, errors, newline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\LP-11\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\prowler\\providers\\aws\\services\\account\\account_maintain_different_contact_details_to_security_billing_and_operations\\account_maintain_different_contact_details_to_security_billing_and_operations.metadata.json'
![Screenshot 2024-10-04 192529](https://github.com/user-attachments/assets/c10d8146-d4b0-4302-924b-4b23699cb325)

### How did you install Prowler?

From pip package (pip install prowler)

### Environment Resource

Workstation

### OS used

windows

### Prowler version

Prowler 4.4.0 (You are running the latest version, yay!)

### Pip version

pip 24.2 from C:\Users\LP-11\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip (python 3.12)

**Comment by MrCloudSec** [comment]
HI @akshaypawar2508, I will try to reproduce the error and come back with a solution. Thanks!

**Comment by MrCloudSec** [comment]
Have you tried on disabling the Path Limit in Windows? @akshaypawar2508 
You can see the instructions [here](https://www.autodesk.com/support/technical/article/caas/sfdcarticles/sfdcarticles/The-Windows-10-default-path-length-limitation-MAX-PATH-is-256-characters.html).

**Comment by akshaypawar2508** [comment]
Hi @sergargar  the path limit was disabled initially. after enabling it , the issue was gone.

Thanks for your help. You can close the issue.

**Comment by MrCloudSec** [comment]
Glad it works @akshaypawar2508, thank you!
